name: Login Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest
    env:
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run login tests
        run: pytest Tests/login_test.py --junitxml=results.xml
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: login-test-results
          path: results.xml
