name: Pytest Login CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run login tests with Pytest
        run: |
          pytest Tests/login_test.py --maxfail=1 --disable-warnings -q

      - name: Archive Pytest results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: .pytest_cache

      - name: Post job summary
        if: always()
        run: |
          echo '### Pytest Job Summary' >> $GITHUB_STEP_SUMMARY
          if [ -f .pytest_cache ]; then echo 'Pytest cache found.' >> $GITHUB_STEP_SUMMARY; else echo 'No pytest cache.' >> $GITHUB_STEP_SUMMARY; fi
