name: Pytest Login CI

on:
  push:
    paths:
      - '**.py'
      - 'Tests/login_test_metadata.json'
  pull_request:
    paths:
      - '**.py'
      - 'Tests/login_test_metadata.json'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest Login Tests
        run: |
          pytest Tests/login_test.py --maxfail=1 --disable-warnings -q
