# This workflow is generated automatically from project metadata for Python testing with Pytest
# It ensures robust, secure, and auditable CI/CD pipeline integration

name: Python Tests (Pytest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  test:
    name: Run Pytest Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest
        env:
          PYTHONPATH: .

      - name: Upload Pytest Results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: ./tests/**/pytest*.xml

      - name: Audit Logging
        run: echo "CI run completed at $(date) by $GITHUB_ACTOR on $GITHUB_SHA"

    timeout-minutes: 20
    continue-on-error: false
